
package todo.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TodoWebService", targetNamespace = "http://service.todo/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TodoWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTask", targetNamespace = "http://service.todo/", className = "todo.service.ListTask")
    @ResponseWrapper(localName = "listTaskResponse", targetNamespace = "http://service.todo/", className = "todo.service.ListTaskResponse")
    public String listTask();

}
