
package todo.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TodoWebServiceService", targetNamespace = "http://service.todo/", wsdlLocation = "http://localhost:8081/todo?wsdl")
public class TodoWebServiceService
    extends Service
{

    private final static URL TODOWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TODOWEBSERVICESERVICE_EXCEPTION;
    private final static QName TODOWEBSERVICESERVICE_QNAME = new QName("http://service.todo/", "TodoWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/todo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TODOWEBSERVICESERVICE_WSDL_LOCATION = url;
        TODOWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TodoWebServiceService() {
        super(__getWsdlLocation(), TODOWEBSERVICESERVICE_QNAME);
    }

    public TodoWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns TodoWebService
     */
    @WebEndpoint(name = "TodoWebServicePort")
    public TodoWebService getTodoWebServicePort() {
        return super.getPort(new QName("http://service.todo/", "TodoWebServicePort"), TodoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TodoWebService
     */
    @WebEndpoint(name = "TodoWebServicePort")
    public TodoWebService getTodoWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.todo/", "TodoWebServicePort"), TodoWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TODOWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TODOWEBSERVICESERVICE_EXCEPTION;
        }
        return TODOWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
